version: '2.1'
services:
  cassandra_node_1:
    container_name: cassandra_node_1
    image: ${CASANDRA_IMAGE}
    ports:
    - 9042:9042
    volumes:
      - ./cassandra_node_1_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=1M
    healthcheck:
      test: ["CMD", "cqlsh"]

  spring_boot_app:
    container_name: spring_boot_app
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - cassandra_node_1
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      cassandra_node_1:
        condition: service_healthy
